version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: authentication-app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - appnet

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      - db
    ports:
      - "5173:5173"
    networks:
      - appnet

  frontend:
    build:
      context: ./frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5173
    depends_on:
      - backend
    ports:
      - "5000:5000"
    networks:
      - appnet

volumes:
  db-data:

networks:
  appnet: